import { validateEnv } from "env";

const envVariables: Record<string, unknown> = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_SANITY_STUDIO_URL: process.env.NEXT_PUBLIC_SANITY_STUDIO_URL,
  NEXT_PUBLIC_BLOB_READ_WRITE_TOKEN:
    process.env.NEXT_PUBLIC_BLOB_READ_WRITE_TOKEN,
  NEXT_PUBLIC_BLOB_STORAGE_NAME: process.env.NEXT_PUBLIC_BLOB_STORAGE_NAME,
  NEXT_PUBLIC_REVALIDATE_SECRET: process.env.NEXT_PUBLIC_REVALIDATE_SECRET,
  NEXT_PUBLIC_SANITY_WEBHOOK_SECRET:
    process.env.NEXT_PUBLIC_SANITY_WEBHOOK_SECRET,
  NEXT_PUBLIC_SANITY_PROJECT_ID: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  NEXT_PUBLIC_SANITY_DATASET: process.env.NEXT_PUBLIC_SANITY_DATASET,
  NEXT_PUBLIC_BLOB_PROJECT_ID: process.env.NEXT_PUBLIC_BLOB_PROJECT_ID,
};
const env = validateEnv(envVariables);

export default env;
